[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 800
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/" }]
gas_reports = ["MundialHook", "MundialToken"]

[profile.ci]
fuzz = { runs = 2000 }

[fuzz]
runs = 512

[rpc_endpoints]
xlayer = "${XLAYER_RPC_URL}"
